### ISSUE TITLE
181012雑談用

### ISSUE THREAD

**Issue by o-kei** [kuarchi-programming-2018/lectures#1]
雑談どうぞ

**Comment by NaohisaYoshida** [comment]
a

**Comment by EmiYot** [comment]
10/25までのassignmentは何のプログラムをどう用いれば、画像として実行できるのでしょうか？

**Comment by o-kei** [comment]
質問ありがとう。
試しに添付のpdfを読みながら順に実行してみてください。それで何ページのどのプログラムで引っかかったか教えてくれればわかりやすいです。


安田渓

2018/10/19 20:23、EmiYot <notifications@github.com>のメール:

**Comment by EmiYot** [comment]
rose.py をspyderを使って、自分で打ち、エラーが出ないところまで、確認しましたが、いつもと同じ▶のボタンをクリックして実行しても、runfile（～）と出るだけで、どのようにすれば画像が表示されるかわかっていないです。

> 質問ありがとう。 試しに添付のpdfを読みながら順に実行してみてください。それで何ページのどのプログラムで引っかかったか教えてくれればわかりやすいです。 安田渓 2018/10/19 20:23、EmiYot <notifications@github.com>のメール:
> […](#)
> 10/25までのassignmentは何のプログラムをどう用いれば、画像として実行できるのでしょうか？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by o-kei** [comment]
実行して、スパイダーのアプリケーションを「最小化」したら見れるかも。スパイダーの後ろで絵が動いている可能性があります

安田渓

2018/10/23 13:11、EmiYot <notifications@github.com>のメール:

**Comment by EmiYot** [comment]
すいません、今やっと理解して、plotroseまでやったら実行できました。お騒がせしました。
